### ISSUE TITLE
js-elevator-challenge

### ISSUE THREAD

**Issue by pablodenadai** [mshang/python-elevator-challenge#3]
Would anyone be keen to develop a JavaScript/Node version of this challenge?

Ps. Thanks @mshang for sharing it :-)

**Comment by mshang** [comment]
Sounds like a great idea. You could run it right in the browser with something like jsfiddle. I won't try to build it, but would love to see it happen.

**Comment by pablodenadai** [comment]
Cool, Python isn't my forte - but I'll try to port it over to JS.

https://github.com/ghpabs/js-elevator-challenge

**Comment by bandali** [comment]
Have you seen [magwo/elevatorsaga](https://github.com/magwo/elevatorsaga) ?

**Comment by pablodenadai** [comment]
No I haven't but thanks for sharing - I'll check it out later on!

**Comment by dyno** [comment]
http://play.elevatorsaga.com/

**Comment by pablodenadai** [comment]
Elevator Saga looks pretty cool - I'll close this ticket as people can refer to their repo if they want a JS implementation.

Thanks! :-)
